import type { CategoryId, Product } from "./types";

const img = {
  kitchenCream:
    "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=1600&q=80",
  kitchenOlive:
    "https://images.unsplash.com/photo-1600489000022-c2086d31f267?auto=format&fit=crop&w=1600&q=80",
  kitchenNavy:
    "https://images.unsplash.com/photo-1600585154340-0ef3c08cad36?auto=format&fit=crop&w=1600&q=80",
  kitchenMarble:
    "https://images.unsplash.com/photo-1556912173-3bb406ef7e77?auto=format&fit=crop&w=1600&q=80",
  workshop:
    "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=1600&q=80",
  woodTable:
    "https://images.unsplash.com/photo-1611269154421-4e27233ac5c7?auto=format&fit=crop&w=1600&q=80",
  bar:
    "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1600&q=80",
  cafe:
    "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1600&q=80",
  pastry:
    "https://images.unsplash.com/photo-1517433670267-08bbd4be890f?auto=format&fit=crop&w=1600&q=80",
  shelf:
    "https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?auto=format&fit=crop&w=1600&q=80",
  entry:
    "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=80",
  garden:
    "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=1600&q=80",
  planter:
    "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=1600&q=80",
  pet:
    "https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=1600&q=80",
  kids:
    "https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=1600&q=80",
  door:
    "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=80",
  sign:
    "https://images.unsplash.com/photo-1452457807411-4979b55760d5?auto=format&fit=crop&w=1600&q=80",
  retail:
    "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1600&q=80",
  desk:
    "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1600&q=80",
};

export const categories: {
  id: CategoryId;
  name: string;
  blurb: string;
  href: string;
}[] = [
  {
    id: "cocinas",
    name: "Cocinas Shaker",
    blurb: "Cocinas inglesas a medida, lacadas y con herrajes de latón.",
    href: "/cocinas",
  },
  {
    id: "hogar",
    name: "Hogar",
    blurb: "Recibidores, puertas, percheros y mobiliario artesanal.",
    href: "/hogar",
  },
  {
    id: "jardin",
    name: "Jardín",
    blurb: "Obeliscos, maceteros Versalles y piezas de exterior.",
    href: "/jardin",
  },
  {
    id: "hosteleria",
    name: "Hostelería",
    blurb: "Barras, islas y mobiliario para bares, cafeterías y ferias.",
    href: "/tienda?categoria=hosteleria",
  },
  {
    id: "comercial",
    name: "Comercial",
    blurb: "Expositores, mostradores y cartelería para negocio.",
    href: "/tienda?categoria=comercial",
  },
  {
    id: "mascotas",
    name: "Mascotas",
    blurb: "Casas, comederos y trepadores de diseño en madera.",
    href: "/tienda?categoria=mascotas",
  },
  {
    id: "infantil",
    name: "Infantil",
    blurb: "Mobiliario lúdico y personalizado para peques.",
    href: "/tienda?categoria=infantil",
  },
  {
    id: "decoracion",
    name: "Decoración",
    blurb: "Estanterías escultóricas, cuadros y letras a medida.",
    href: "/tienda?categoria=decoracion",
  },
];

export const products: Product[] = [
  {
    id: "p-cocina-britanica",
    sku: "SC-COC-001",
    slug: "cocina-estilo-britanico-ingles-artesanal",
    name: "Cocina estilo británico inglés artesanal a medida",
    price: 1200,
    category: "cocinas",
    short:
      "Cocina Shaker de inspiración inglesa, fabricada a mano en Sevilla para toda España.",
    description:
      "Diseñamos y fabricamos cocinas Shaker tipo inglés que combinan elegancia, funcionalidad y durabilidad. Puertas enmarcadas clásicas, lacado a medida y herrajes de latón. El precio indicado es un módulo de muestra; cada proyecto se presupuesta según metros, acabados y encimera.",
    materials: ["MDF hidrófugo lacado", "Madera maciza", "Herrajes de latón"],
    leadTimeDays: 45,
    madeToMeasure: true,
    featured: true,
    stock: 1,
    cost: 620,
    tags: ["shaker", "inglesa", "a medida"],
    color: "#EDE4D4",
    image: img.kitchenCream,
    mesh: "kitchen",
  },
  {
    id: "p-mobiliario-bares",
    sku: "SC-HOS-001",
    slug: "mobiliario-equipamiento-bares",
    name: "Mobiliario y equipamiento para bares",
    price: 2333,
    category: "hosteleria",
    short: "Conjunto de mobiliario de bar artesanal listo para negocio.",
    description:
      "Equipamiento de bar fabricado en taller: estructura robusta, acabado lacado y zona de trabajo pensada para servicio diario. Personalizable en color Shaker, madera y latón.",
    materials: ["Tablero hidrófugo", "Madera maciza", "Laca satinada"],
    leadTimeDays: 30,
    madeToMeasure: true,
    featured: true,
    stock: 1,
    cost: 1100,
    tags: ["bar", "hostelería"],
    color: "#2C3A56",
    image: img.bar,
    mesh: "bar",
  },
  {
    id: "p-stand-hot-dog",
    sku: "SC-HOS-002",
    slug: "mueble-stand-isla-hot-dog",
    name: "Mueble stand isla centro comercial hot dog",
    price: 2400,
    category: "hosteleria",
    short: "Isla comercial compacta para food court o centro comercial.",
    description:
      "Stand isla pensado para hot dog y street food: mostrador de servicio, almacenaje interior y acabado resistente al uso intensivo. Fabricación a medida según hueco y normativa del centro.",
    materials: ["Tablero compacto", "Laca", "Encimera de trabajo"],
    leadTimeDays: 28,
    madeToMeasure: true,
    featured: false,
    stock: 1,
    cost: 1250,
    tags: ["isla", "retail"],
    color: "#6A7349",
    image: img.retail,
    mesh: "counter",
  },
  {
    id: "p-barra-eventos",
    sku: "SC-HOS-003",
    slug: "barra-eventos-celebraciones",
    name: "Barra para eventos y celebraciones",
    price: 299,
    category: "hosteleria",
    short: "Barra ligera y elegante para eventos, bodas y pop-ups.",
    description:
      "Barra desmontable de línea Shaker para celebraciones. Fácil de transportar, acabado premium y frontal personalizable con color de marca.",
    materials: ["MDF lacado", "Madera"],
    leadTimeDays: 14,
    madeToMeasure: true,
    featured: false,
    stock: 2,
    cost: 120,
    tags: ["eventos", "barra"],
    color: "#EDE4D4",
    image: img.cafe,
    mesh: "bar",
  },
  {
    id: "p-barra-alta",
    sku: "SC-HOS-004",
    slug: "barra-alta-cafeteria-bar",
    name: "Barra alta para cafetería / bar",
    price: 344,
    category: "hosteleria",
    short: "Barra alta de servicio con estética británica.",
    description:
      "Barra alta para cafetería o bar, con frente Shaker y tablero de trabajo. Ideal para locales que buscan un look inglés atemporal sin obra completa.",
    materials: ["MDF lacado", "Tablero de trabajo"],
    leadTimeDays: 16,
    madeToMeasure: true,
    featured: false,
    stock: 2,
    cost: 140,
    tags: ["cafetería", "barra"],
    color: "#2C3A56",
    image: img.cafe,
    mesh: "bar",
  },
  {
    id: "p-pasteleria",
    sku: "SC-HOS-005",
    slug: "muebles-pasteleria-galletas",
    name: "Muebles pastelería / galletas",
    price: 355,
    category: "hosteleria",
    short: "Expositor dulce de madera para pastelería y cookie shop.",
    description:
      "Mobiliario de pastelería con bandejas y frente artesanal. Pensado para galletas, napolitanas y take-away, con acabado fácil de limpiar.",
    materials: ["Madera", "Laca alimentaria"],
    leadTimeDays: 18,
    madeToMeasure: true,
    featured: false,
    stock: 1,
    cost: 150,
    tags: ["pastelería", "expositor"],
    color: "#EDE4D4",
    image: img.pastry,
    mesh: "shelf",
  },
  {
    id: "p-barra-azul",
    sku: "SC-HOS-006",
    slug: "barra-bar-azul-marino-madera",
    name: "Barra de bar azul marino con madera",
    price: 299,
    category: "hosteleria",
    short: "Barra bicolor: azul profundo Shaker y madera natural.",
    description:
      "Reinterpretación intensa del estilo Shaker en azul marino, combinada con madera natural. La misma paleta de las cocinas de autor, ahora para el local.",
    materials: ["MDF lacado azul", "Madera natural"],
    leadTimeDays: 16,
    madeToMeasure: true,
    featured: true,
    stock: 1,
    cost: 130,
    tags: ["azul", "bar", "shaker"],
    color: "#2C3A56",
    image: img.bar,
    mesh: "bar",
  },
  {
    id: "p-estanteria-arbol",
    sku: "SC-DEC-001",
    slug: "estanteria-madera-forma-arbol",
    name: "Estantería de madera forma árbol artesanal",
    price: 150,
    category: "decoracion",
    short: "Estantería escultórica en forma de árbol, hecha a mano.",
    description:
      "Pieza de autor: estantería árbol en madera, pensada como arte útil para salón, recibidor o dormitorio infantil. Cada unidad se fabrica a mano en el taller de Sevilla.",
    materials: ["Madera maciza"],
    leadTimeDays: 12,
    madeToMeasure: true,
    featured: false,
    stock: 2,
    cost: 55,
    tags: ["estantería", "arte"],
    color: "#8A6A45",
    image: img.shelf,
    mesh: "shelf",
  },
  {
    id: "p-trepar-gato",
    sku: "SC-PET-001",
    slug: "mobiliario-trepar-gato-pared",
    name: "Mobiliario trepar gato de pared en madera",
    price: 275,
    category: "mascotas",
    short: "Ruta de pared para gatos, diseño de carpintería.",
    description:
      "Sistema de peldaños y plataformas de madera para gatos. Se instala en pared, combina juego y estética de mobiliario de diseño — nada de rascadores genéricos.",
    materials: ["Madera", "Fieltro opcional"],
    leadTimeDays: 10,
    madeToMeasure: true,
    featured: false,
    stock: 2,
    cost: 90,
    tags: ["gato", "pared"],
    color: "#8A6A45",
    image: img.pet,
    mesh: "pet",
  },
  {
    id: "p-caseta-mascota",
    sku: "SC-PET-002",
    slug: "caseta-perro-gato-moderna-diseno",
    name: "Caseta para perro y gato moderna de diseño",
    price: 300,
    category: "mascotas",
    short: "Caseta de diseño, más mueble que jaula.",
    description:
      "Caseta contemporánea de madera para perro o gato. Líneas limpias, ventilación estudiada y acabado que encaja en un interior Shaker o nórdico.",
    materials: ["Madera", "Laca"],
    leadTimeDays: 14,
    madeToMeasure: true,
    featured: false,
    stock: 2,
    cost: 110,
    tags: ["caseta", "mascota"],
    color: "#EDE4D4",
    image: img.pet,
    mesh: "pet",
  },
  {
    id: "p-cuadro-mascota",
    sku: "SC-DEC-002",
    slug: "cuadro-pared-mascota-minimalista",
    name: "Cuadro de pared mascota minimalista",
    price: 70,
    category: "decoracion",
    short: "Silueta de gato o perro en madera, minimalista.",
    description:
      "Cuadro-relieve de mascota en madera. Personalizable con raza o silueta. Un detalle pequeño, muy fotogénico, para recibidor o rincón de mascotas.",
    materials: ["Madera", "Pintura mate"],
    leadTimeDays: 7,
    madeToMeasure: true,
    featured: false,
    stock: 5,
    cost: 18,
    tags: ["cuadro", "mascota"],
    color: "#1A1612",
    image: img.sign,
    mesh: "sign",
  },
  {
    id: "p-casa-aero",
    sku: "SC-PET-003",
    slug: "casa-comedor-mascotas-aero",
    name: "Casa-comedor para mascotas Aero",
    price: 400,
    category: "mascotas",
    short: "Casa y comedero integrados, diseño Aero.",
    description:
      "Mueble 2 en 1: refugio y estación de alimentación. El modelo Aero ordena el comedero, esconde el pienso y viste la estancia como un mueble más.",
    materials: ["Madera", "Laca", "Acero"],
    leadTimeDays: 18,
    madeToMeasure: true,
    featured: true,
    stock: 1,
    cost: 160,
    tags: ["comedero", "casa"],
    color: "#EDE4D4",
    image: img.pet,
    mesh: "pet",
  },
  {
    id: "p-casa-gatos",
    sku: "SC-PET-004",
    slug: "casa-gatos-madera-diseno",
    name: "Casa para gatos de madera de diseño",
    price: 400,
    category: "mascotas",
    short: "Torre-casa para gatos con estética de mobiliario.",
    description:
      "Casa para gatos en madera de diseño, con huecos, plataformas y acabado de ebanistería. Pensada para salones donde el rascador no puede desentonar.",
    materials: ["Madera maciza", "Contrachapado"],
    leadTimeDays: 16,
    madeToMeasure: true,
    featured: false,
    stock: 1,
    cost: 155,
    tags: ["gato", "casa"],
    color: "#8A6A45",
    image: img.pet,
    mesh: "pet",
  },
  {
    id: "p-carteles-logo",
    sku: "SC-COM-001",
    slug: "carteles-personalizables-logo-marca",
    name: "Carteles personalizables con logo y letras de marca",
    price: 200,
    category: "comercial",
    short: "Rótulo de madera con tu logo, letras y marca.",
    description:
      "Cartelería de madera para locales, ferias y escaparates. Letras caladas o en relieve, logo de marca y lacado en la paleta Shaker o corporativa.",
    materials: ["Madera", "Laca", "Vinilo opcional"],
    leadTimeDays: 10,
    madeToMeasure: true,
    featured: false,
    stock: 3,
    cost: 70,
    tags: ["logo", "rótulo"],
    color: "#1A1612",
    image: img.sign,
    mesh: "sign",
  },
  {
    id: "p-obelisco",
    sku: "SC-JAR-001",
    slug: "obelisco-jardin-madera-blanco",
    name: "Obelisco de jardín de madera blanco artesanal",
    price: 400,
    category: "jardin",
    short: "Obelisco inglés blanco para trepadoras y jardín formal.",
    description:
      "Obelisco de jardín de inspiración inglesa, lacado en blanco. Estructura artesanal para rosales, jazmines o como eje vertical en un parterre a la manera de un jardín británico.",
    materials: ["Madera tratada", "Laca exterior"],
    leadTimeDays: 14,
    madeToMeasure: true,
    featured: true,
    stock: 2,
    cost: 140,
    tags: ["jardín", "inglés"],
    color: "#F4EFE6",
    image: img.garden,
    mesh: "planter",
  },
  {
    id: "p-estanteria-diseno",
    sku: "SC-DEC-003",
    slug: "estanteria-diseno-personalizable-madera",
    name: "Estantería de diseño personalizable en madera",
    price: 300,
    category: "decoracion",
    short: "Estantería arte, a medida en medidas y color.",
    description:
      "Estantería de diseño que se comporta como una pieza de arte. Personalizable en módulos, color lacado y madera vista.",
    materials: ["Madera", "Laca"],
    leadTimeDays: 14,
    madeToMeasure: true,
    featured: false,
    stock: 2,
    cost: 110,
    tags: ["estantería", "a medida"],
    color: "#6A7349",
    image: img.shelf,
    mesh: "shelf",
  },
  {
    id: "p-repisa-plantas",
    sku: "SC-DEC-004",
    slug: "repisa-decorativa-madera-plantas",
    name: "Repisa decorativa de madera para plantas",
    price: 60,
    category: "decoracion",
    short: "Repisa ligera para plantas y objetos.",
    description:
      "Repisa de diseño para plantas, velas y cerámica. Perfil fino, madera honesta y anclaje limpio. Un esencial asequible de la colección.",
    materials: ["Madera"],
    leadTimeDays: 7,
    madeToMeasure: true,
    featured: false,
    stock: 6,
    cost: 18,
    tags: ["repisa", "plantas"],
    color: "#8A6A45",
    image: img.shelf,
    mesh: "shelf",
  },
  {
    id: "p-organizadores",
    sku: "SC-HOG-001",
    slug: "organizadores-pared-mesa-medida",
    name: "Organizadores de pared y mesa a medida",
    price: 120,
    category: "hogar",
    short: "Organización visible, carpintería invisible.",
    description:
      "Organizadores de pared y escritorio fabricados a medida. Bandejas, cajetines y listones para hall, cocina o estudio.",
    materials: ["Madera", "Laca"],
    leadTimeDays: 10,
    madeToMeasure: true,
    featured: false,
    stock: 4,
    cost: 40,
    tags: ["organización", "hogar"],
    color: "#EDE4D4",
    image: img.desk,
    mesh: "shelf",
  },
  {
    id: "p-zapatero-metal",
    sku: "SC-HOG-002",
    slug: "zapatero-diseno-metal-blanco-negro",
    name: "Zapatero diseño metal blanco y negro",
    price: 300,
    category: "hogar",
    short: "Zapatero mixto madera-metal, gráfico y contemporáneo.",
    description:
      "Zapatero de líneas gráficas en blanco y negro, con estructura metálica y madera. Encaja en entradas modernas y mudrooms.",
    materials: ["Metal", "Madera", "Laca"],
    leadTimeDays: 16,
    madeToMeasure: true,
    featured: false,
    stock: 1,
    cost: 120,
    tags: ["zapatero", "entrada"],
    color: "#1A1612",
    image: img.entry,
    mesh: "shelf",
  },
  {
    id: "p-estanterias-arte",
    sku: "SC-DEC-005",
    slug: "estanterias-decorativas-arte-diseno",
    name: "Estanterías decorativas de arte y diseño",
    price: 350,
    category: "decoracion",
    short: "Estantería escultura para objetos y libros.",
    description:
      "Estantería pensada como pieza de galería: ritmos, vacíos y madera. Ideal para comedores y salones con pretensión editorial.",
    materials: ["Madera maciza"],
    leadTimeDays: 16,
    madeToMeasure: true,
    featured: false,
    stock: 1,
    cost: 130,
    tags: ["arte", "estantería"],
    color: "#8A6A45",
    image: img.shelf,
    mesh: "shelf",
  },
  {
    id: "p-mesa-infantil",
    sku: "SC-INF-001",
    slug: "mesa-sillas-infantiles-madera-animales",
    name: "Mesa y sillas infantiles de madera con animales",
    price: 500,
    category: "infantil",
    short: "Set infantil artesanal con siluetas de animales.",
    description:
      "Mesa y sillas para peques, en madera y con respaldo de animales. Seguro, estable y con el mismo cuidado de lacado que el mobiliario adulto.",
    materials: ["Madera", "Laca infantil"],
    leadTimeDays: 18,
    madeToMeasure: true,
    featured: false,
    stock: 1,
    cost: 180,
    tags: ["niños", "mesa"],
    color: "#EDE4D4",
    image: img.kids,
    mesh: "kids",
  },
  {
    id: "p-mueble-tiburon",
    sku: "SC-INF-002",
    slug: "mueble-infantil-tiburon-madera",
    name: "Mueble infantil tiburón de madera artesano",
    price: 350,
    category: "infantil",
    short: "Aparador-juguete en forma de tiburón.",
    description:
      "Mueble infantil escultórico: un tiburón de madera que guarda juguetes. Pieza firma del taller, muy demandada en habitaciones temáticas.",
    materials: ["Madera", "Laca"],
    leadTimeDays: 20,
    madeToMeasure: true,
    featured: true,
    stock: 1,
    cost: 140,
    tags: ["tiburón", "infantil"],
    color: "#2C3A56",
    image: img.kids,
    mesh: "kids",
  },
  {
    id: "p-escritorio-plegable",
    sku: "SC-HOG-003",
    slug: "escritorio-organizador-plegable-pared",
    name: "Escritorio organizador plegable de pared",
    price: 320,
    category: "hogar",
    short: "Secretario de pared que desaparece cuando no se usa.",
    description:
      "Escritorio plegable de pared con organizador interior. Solución Shaker: cuando se cierra, es un panel elegante; cuando se abre, un estudio completo.",
    materials: ["MDF lacado", "Madera", "Herrajes"],
    leadTimeDays: 16,
    madeToMeasure: true,
    featured: false,
    stock: 2,
    cost: 125,
    tags: ["escritorio", "plegable"],
    color: "#EDE4D4",
    image: img.desk,
    mesh: "table",
  },
  {
    id: "p-goku",
    sku: "SC-INF-003",
    slug: "estanteria-repisa-goku-circular",
    name: "Estantería-repisa Goku circular personalizada",
    price: 200,
    category: "infantil",
    short: "Repisa circular personalizada de personaje.",
    description:
      "Estantería circular personalizada (Goku u otro personaje). Encargo frecuente para habitaciones infantiles y fans. Se fabrica a partir de silueta acordada.",
    materials: ["Madera", "Laca"],
    leadTimeDays: 12,
    madeToMeasure: true,
    featured: false,
    stock: 2,
    cost: 70,
    tags: ["goku", "personalizado"],
    color: "#C4A574",
    image: img.kids,
    mesh: "kids",
  },
  {
    id: "p-heladeria",
    sku: "SC-HOS-007",
    slug: "estanteria-heladeria-personalizada",
    name: "Estantería de heladería personalizada",
    price: 200,
    category: "hosteleria",
    short: "Expositor de heladería con branding del local.",
    description:
      "Estantería para heladería o ice-cream shop, con huecos para tarrinas, cono display y zona de marca. Personalizable con el color corporativo.",
    materials: ["Madera", "Laca"],
    leadTimeDays: 14,
    madeToMeasure: true,
    featured: false,
    stock: 1,
    cost: 75,
    tags: ["heladería", "retail"],
    color: "#EDE4D4",
    image: img.pastry,
    mesh: "shelf",
  },
  {
    id: "p-mudroom",
    sku: "SC-HOG-004",
    slug: "mueble-entrada-zapatero-mudroom",
    name: "Mueble de entrada / zapatero mudroom",
    price: 1300,
    category: "hogar",
    short: "Mudroom inglés: banco, ganchos, zapatero y panel Shaker.",
    description:
      "Mueble de entrada tipo mudroom británico: zapatero, perchero, banco y panel enmarcado. Blanco y madera, el mismo lenguaje de las cocinas Shaker. Pieza estrella para halls sevillanos y áticos de Madrid.",
    materials: ["MDF lacado", "Madera", "Latón"],
    leadTimeDays: 28,
    madeToMeasure: true,
    featured: true,
    stock: 1,
    cost: 560,
    tags: ["mudroom", "entrada", "shaker"],
    color: "#EDE4D4",
    image: img.entry,
    mesh: "counter",
  },
  {
    id: "p-puerta",
    sku: "SC-HOG-005",
    slug: "puerta-madera-artesanal-clasica",
    name: "Puerta de madera artesanal clásica a medida",
    price: 400,
    category: "hogar",
    short: "Puerta clásica a medida, alma Shaker.",
    description:
      "Puertas de madera artesanales, de línea clásica inglesa. Fabricadas a hueco, con moldura Shaker y acabado lacado o madera vista.",
    materials: ["Madera maciza", "Laca"],
    leadTimeDays: 21,
    madeToMeasure: true,
    featured: false,
    stock: 2,
    cost: 160,
    tags: ["puerta", "a medida"],
    color: "#8A6A45",
    image: img.door,
    mesh: "door",
  },
  {
    id: "p-macetero-versalles",
    sku: "SC-JAR-002",
    slug: "macetero-madera-estilo-versalles",
    name: "Macetero de madera estilo Versalles artesanal",
    price: 975,
    category: "jardin",
    short: "Cajón Versalles de madera, jardín formal a la inglesa.",
    description:
      "Macetero estilo Versalles, pieza de jardín clásico. Carpintería de exterior, lacado blanco y proporciones de orangerie. Ideal para naranjos, olivos o la entrada de un chalet.",
    materials: ["Madera tratada", "Laca exterior"],
    leadTimeDays: 21,
    madeToMeasure: true,
    featured: true,
    stock: 1,
    cost: 380,
    tags: ["versalles", "jardín"],
    color: "#F4EFE6",
    image: img.garden,
    mesh: "planter",
  },
  {
    id: "p-letra-bebe",
    sku: "SC-INF-004",
    slug: "letra-madera-personalizada-nombre-bebe",
    name: "Letra de madera personalizada para bebé",
    price: 50,
    category: "infantil",
    short: "Inicial o nombre en madera para natalicio.",
    description:
      "Letra o nombre en madera para habitación de bebé. Corte preciso, canto suave y lacado en la paleta del cuarto. Regalo de taller con alma.",
    materials: ["Madera", "Laca"],
    leadTimeDays: 7,
    madeToMeasure: true,
    featured: false,
    stock: 8,
    cost: 12,
    tags: ["bebé", "nombre"],
    color: "#EDE4D4",
    image: img.kids,
    mesh: "sign",
  },
  {
    id: "p-cartel-madera",
    sku: "SC-COM-002",
    slug: "cartel-personalizado-madera-logo",
    name: "Cartel personalizado de madera con logo",
    price: 199,
    category: "comercial",
    short: "Cartel de marca en madera, para local o feria.",
    description:
      "Cartel de madera con logo de marca, listo para pared o peana. Acabado de ebanistería, no de plotter. Muy usado en pop-ups y estudios.",
    materials: ["Madera", "Laca"],
    leadTimeDays: 10,
    madeToMeasure: true,
    featured: false,
    stock: 3,
    cost: 65,
    tags: ["cartel", "logo"],
    color: "#1A1612",
    image: img.sign,
    mesh: "sign",
  },
  {
    id: "p-expositor-desmontable",
    sku: "SC-COM-003",
    slug: "expositor-madera-desmontable-ferias",
    name: "Expositor de madera desmontable para ferias",
    price: 399,
    category: "comercial",
    short: "Display ferial desmontable, transporte fácil.",
    description:
      "Expositor desmontable para ferias y tiendas. Encaja en furgoneta, se monta en minutos y luce como mobiliario permanente.",
    materials: ["Madera", "Herrajes"],
    leadTimeDays: 14,
    madeToMeasure: true,
    featured: false,
    stock: 2,
    cost: 150,
    tags: ["feria", "expositor"],
    color: "#8A6A45",
    image: img.retail,
    mesh: "counter",
  },
  {
    id: "p-expositores-tiendas",
    sku: "SC-COM-004",
    slug: "expositores-madera-ferias-tiendas",
    name: "Expositores de madera para ferias y tiendas",
    price: 400,
    category: "comercial",
    short: "Familia de expositores para retail y feria.",
    description:
      "Expositores de madera para producto: cosmética, cerámica, moda o gourmet. Se fabrican en serie corta con la identidad del cliente.",
    materials: ["Madera", "Laca"],
    leadTimeDays: 14,
    madeToMeasure: true,
    featured: false,
    stock: 2,
    cost: 155,
    tags: ["retail", "feria"],
    color: "#EDE4D4",
    image: img.retail,
    mesh: "shelf",
  },
  {
    id: "p-perchero-ingles",
    sku: "SC-HOG-006",
    slug: "mueble-perchero-artesanal-madera-metal-ingles",
    name: "Mueble perchero artesanal madera y metal inglés",
    price: 1300,
    category: "hogar",
    short: "Hall stand inglés: madera, metal y presencia.",
    description:
      "Perchero de recibidor de inspiración inglesa, combinación de madera y metal. Ganchos, espejo opcional y cajón inferior. Una pieza de carácter para entradas con techo alto.",
    materials: ["Madera maciza", "Metal", "Latón"],
    leadTimeDays: 28,
    madeToMeasure: true,
    featured: true,
    stock: 1,
    cost: 540,
    tags: ["perchero", "inglés"],
    color: "#8A6A45",
    image: img.entry,
    mesh: "counter",
  },
  {
    id: "p-banco-recibidor",
    sku: "SC-HOG-007",
    slug: "banco-recibidor-artesanal-madera",
    name: "Banco recibidor artesanal de madera",
    price: 1000,
    category: "hogar",
    short: "Banco de hall con almacenaje y línea clásica.",
    description:
      "Banco de recibidor artesanal, con o sin cajones. Madera noble, asiento cómodo y proporción de mobiliario inglés. Encaja bajo percheros Shaker.",
    materials: ["Madera maciza"],
    leadTimeDays: 21,
    madeToMeasure: true,
    featured: false,
    stock: 1,
    cost: 390,
    tags: ["banco", "recibidor"],
    color: "#8A6A45",
    image: img.entry,
    mesh: "table",
  },
  {
    id: "p-mueble-recibidor",
    sku: "SC-HOG-008",
    slug: "mueble-recibidor-artesano-madera",
    name: "Mueble recibidor artesano de madera",
    price: 1300,
    category: "hogar",
    short: "Consola de recibidor a medida, carpintería de autor.",
    description:
      "Mueble de recibidor completo: cajones, estante para llaves y superficie para lámpara. Fabricado a hueco para que el hall quede impecable.",
    materials: ["Madera", "Laca", "Latón"],
    leadTimeDays: 24,
    madeToMeasure: true,
    featured: false,
    stock: 1,
    cost: 520,
    tags: ["recibidor", "consola"],
    color: "#EDE4D4",
    image: img.entry,
    mesh: "counter",
  },
  {
    id: "p-batman",
    sku: "SC-INF-005",
    slug: "repisa-batman-madera-negra",
    name: "Repisa Batman de madera negra",
    price: 50,
    category: "infantil",
    short: "Silueta Batman en madera negra, para pared.",
    description:
      "Repisa o silueta Batman en madera negra. Encargo rápido, gran efecto en habitación infantil o rincón friki adulto.",
    materials: ["Madera", "Laca negra"],
    leadTimeDays: 7,
    madeToMeasure: true,
    featured: false,
    stock: 4,
    cost: 14,
    tags: ["batman", "repisa"],
    color: "#1A1612",
    image: img.kids,
    mesh: "sign",
  },
  {
    id: "p-cuadro-geometrico",
    sku: "SC-DEC-006",
    slug: "cuadro-decorativo-minimalista-geometrico",
    name: "Cuadro decorativo minimalista geométrico",
    price: 200,
    category: "decoracion",
    short: "Relieve geométrico de madera, arte de pared.",
    description:
      "Cuadro de relieve geométrico en madera. Pieza minimalista que dialoga con las puertas Shaker: ritmo, sombra y materia.",
    materials: ["Madera", "Laca"],
    leadTimeDays: 10,
    madeToMeasure: true,
    featured: false,
    stock: 2,
    cost: 70,
    tags: ["arte", "geométrico"],
    color: "#EDE4D4",
    image: img.sign,
    mesh: "sign",
  },
  {
    id: "p-ballena",
    sku: "SC-DEC-007",
    slug: "estanteria-madera-forma-cola-ballena",
    name: "Estantería de madera forma cola de ballena",
    price: 199,
    category: "decoracion",
    short: "Estantería cola de ballena, pieza escultórica.",
    description:
      "Estantería en forma de cola de ballena. Madera artesanal, muy fotogénica para estudios, tiendas náuticas y habitaciones infantiles.",
    materials: ["Madera maciza"],
    leadTimeDays: 12,
    madeToMeasure: true,
    featured: false,
    stock: 2,
    cost: 70,
    tags: ["ballena", "estantería"],
    color: "#8A6A45",
    image: img.shelf,
    mesh: "shelf",
  },
  {
    id: "p-mostrador",
    sku: "SC-COM-005",
    slug: "mostrador-expositor-negocio",
    name: "Mostrador expositor para negocio",
    price: 4500,
    category: "comercial",
    short: "Mostrador de autor para boutique, estudio o gastronomía.",
    description:
      "Mostrador expositor de gran formato para negocio. Carpintería a medida, zona de caja, vitrina y acabado de cocina Shaker si se desea. El buque insignia comercial del taller.",
    materials: ["MDF hidrófugo", "Madera", "Encimera", "Latón"],
    leadTimeDays: 40,
    madeToMeasure: true,
    featured: true,
    stock: 1,
    cost: 1900,
    tags: ["mostrador", "negocio"],
    color: "#2C3A56",
    image: img.retail,
    mesh: "counter",
  },
  {
    id: "p-mesa-maciza",
    sku: "SC-HOG-009",
    slug: "mesa-artesanal-madera-maciza",
    name: "Mesa artesanal de madera maciza",
    price: 890,
    category: "hogar",
    short: "Mesa de comedor fabricada a mano, esencia de la madera natural.",
    description:
      "Esta mesa ha sido fabricada a mano en nuestro taller, cuidando cada detalle y respetando la esencia de la madera natural. Diseñada para aportar calidez y carácter al espacio, combina tradición, resistencia y elegancia atemporal.",
    materials: ["Madera maciza"],
    leadTimeDays: 21,
    madeToMeasure: true,
    featured: true,
    stock: 1,
    cost: 340,
    tags: ["mesa", "comedor"],
    color: "#8A6A45",
    image: img.woodTable,
    mesh: "table",
  },
];

export const portfolio = [
  {
    slug: "cocina-verde-oliva-marmol-laton",
    title: "Cocina Shaker verde oliva con encimera de mármol y latón",
    text: "Diseñamos esta cocina estilo Shaker en tono verde oliva, combinando puertas enmarcadas clásicas con tiradores de latón envejecido y una elegante encimera de mármol natural. La iluminación integrada y los muebles a medida aportan funcionalidad y sofisticación, creando un espacio luminoso, cálido y atemporal. Fabricamos cocinas Shaker a medida en Sevilla y para toda España, cuidando cada detalle artesanal para lograr un resultado exclusivo y duradero.",
    image: img.kitchenOlive,
    finish: "oliva" as const,
  },
  {
    slug: "cocina-blanco-crema",
    title: "Cocina Shaker en blanco crema",
    text: "Una cocina Shaker luminosa y atemporal que combina líneas clásicas con acabados contemporáneos. El mobiliario lacado en tono crema y los tiradores en latón aportan elegancia y calidez, mientras que la encimera de mármol refuerza la sensación de calidad y durabilidad. Un espacio pensado para perdurar en el tiempo sin perder sofisticación.",
    image: img.kitchenCream,
    finish: "crema" as const,
  },
  {
    slug: "cocina-azul-profundo",
    title: "Cocina Shaker en azul profundo",
    text: "Una reinterpretación más intensa del estilo Shaker, donde el azul profundo aporta carácter y personalidad al espacio. La combinación con madera natural y encimeras claras equilibra tradición y modernidad, creando una cocina acogedora, funcional y con gran presencia estética. Diseño artesanal pensado para quienes buscan un estilo distintivo sin renunciar a la elegancia clásica.",
    image: img.kitchenNavy,
    finish: "navy" as const,
  },
  {
    slug: "mesa-artesanal-madera-maciza",
    title: "Mesa artesanal de madera maciza",
    text: "Esta mesa ha sido fabricada a mano en nuestro taller, cuidando cada detalle y respetando la esencia de la madera natural. Diseñada para aportar calidez y carácter al espacio, combina tradición, resistencia y elegancia atemporal.",
    image: img.woodTable,
    finish: "crema" as const,
  },
];

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function productsByCategory(category?: CategoryId | "all") {
  if (!category || category === "all") return products;
  return products.filter((p) => p.category === category);
}

export function featuredProducts() {
  return products.filter((p) => p.featured);
}

export const categoryLabel: Record<CategoryId, string> = Object.fromEntries(
  categories.map((c) => [c.id, c.name]),
) as Record<CategoryId, string>;
